# Generated by Django 4.2 on 2023-07-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=30)),
                ('pl_email', models.EmailField(max_length=20)),
                ('pl_phone', models.IntegerField()),
                ('pl_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
