# Generated by Django 4.2.3 on 2023-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='pl_email',
            field=models.EmailField(max_length=100),
        ),
    ]
