# Generated by Django 4.2 on 2023-08-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0002_alter_place_pl_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='pl_image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
