# Generated by Django 4.2.3 on 2023-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('seondname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=29)),
                ('salary', models.FloatField(max_length=23)),
            ],
        ),
    ]
