# Generated by Django 4.2 on 2023-07-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='detail',
        ),
    ]
